seed: 0

steps_per_task: 50000

eval_every: 5000

det_eval_episodes: 10
stoch_eval_episodes: 10

batch_size: 256
replay_size: 1000000

start_steps: 5000
update_after: 1000
update_every: 50

device: cpu

wandb:
  mode: online
  project: crl-cw
  group: cw10-pilot